### ISSUE TITLE
HDMI: OrangePi PC2 show nothing

### ISSUE THREAD

**Issue by Jeepgoing** [orangepi-xunlong/OrangePi_Build#27]
hi, all:
  i am now testing OrangePi PC2 board, and i met an issue, when i download `Ubuntu_Desktop_Xenial_xfce4_PC2_CN_V1_0_0.img` (from OrangePI official network) to the board, my monitor can show login interface, but when i download `OrangePiH5_PC2.img`(compiled by the code from github), my monitor show nothing(exactly to say from show "HDMI" to nothing), and printk some errors as below:
`[DISP] disp_boot_para_parse,line:347:of_property_read disp.init_disp fail`

so who can give me some advise

the same as #10

**Comment by wormyrocks** [comment]
Hi,
I'm getting an identical error, although with Android 7.1.0 on the Nanopi K1 Prime (Allwinner H5). I am trying to add a portrait display mode to the kernel.
Do you know if the values accessed by of_property_read are supposed to be the ones generated by sys_config.fex, or do they come from somewhere else?
I checked and [the default sys_config.fex](https://gitlab.com/friendlyelec/h5_lichee/blob/master-android7.0/tools/pack/chips/sun50iw2p1/configs/cheetah-p1/board/sys_config_nanopi-k1-plus.fex#L445) (at least for Nanopi K1) seems to have a [disp] section header rather than a [disp_init] section header; do you think it's a typo? I get the same error, and dmesg does not seem to be logging any of the changes I make to the display parameters when I rebuild the fex.
But this solution is already very helpful, I will try, thank you :)
