### ISSUE TITLE
downloading issue: no packet lib32z1 lib32z1-dev

### ISSUE THREAD

**Issue by qdsjx1989** [orangepi-xunlong/OrangePi_Build#9]
when I downloading the kernel file:
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package lib32z1
E: Unable to locate package lib32z1-dev

**Comment by JYKeith123** [comment]
I found this libraries are not for ARM processor. - [link](https://github.com/nylas/sync-engine/issues/414)
So I commentize it from [this](https://github.com/orangepi-xunlong/OrangePi_Build/blob/master/lib/PrepareTool.sh).
But still there is a problem. I'm building os for i96 (RDA or 2G IOT), but 
they have been using H3 toolchain I don't know why.

https://github.com/orangepi-xunlong/OrangePi_Build/blob/master/lib/i96SDK_BuildEnvironment.sh
https://github.com/orangepi-xunlong/OrangePi_Build/blob/master/lib/RDASDK_BuildEnvironment.sh
both use below toolchain.
`toolchain="https://codeload.github.com/orangepi-xunlong/OrangePiH3_toolchain/zip/master"`

I tried to build my own linux with my orangepi i96, and of course, it failed because the toolchain for H3 can not be executed on i96.

**Comment by orangepi-xunlong** [comment]
It is recommended to use the SDK on Ubuntu 14.04.

and i96 and h3 have the same toolchain.

Thanks!

**Comment by RakibFiha** [comment]
I am having this same issue.
